Highlights of this commit are:
* add NodeManagerWhite unit test

* change kind::APPLY to kind::APPLY_UF

* better APPLY handling: operators are no longer considered children

* more efficient pool lookup; the NodeValue doesn't have to be as fully constructed for the lookup to proceed

* extend DSL for kind declarations
  + new "theory" command declares a theory and its header.  theory_def.h no longer required.
  + arity enforced on operators
  + constant mapping, hashing, equality

* CONSTANT metakinds supported (via Node::getConst<T>(), for example, Node::getConst<CVC4::Rational>() gets a Rational out of a Node (assuming it is of CONST_RATIONAL kind)

* added CONST_RATIONAL and CONST_INTEGER kinds

* builtin operators (AND, OR, PLUS, etc..) returned by Node::getOperator() are now CONSTANT metakind and are created by NodeManager

* Pretty-printing of Nodes now has a depth limit settable by a stream manipulator (e.g. "cout << Node::setdepth(5) << m << endl;" prints DAG rooted at m to a depth of 5)

* getters added to Node, TNode, NodeValue, etc., for operators and metakinds

* build-time generators for kind.h, metakind.h, and theoryof_table.h headers now have a simpler design and flag errors better, and the templates (kind_template.h etc.) are easier to understand.

* DISTINCT is now a kind, and the SMT parser now passes through DISTINCT nodes instead of blowing them up into ANDs.  Until theory rewriting is online, though, DISTINCTs are directly blown up into conjunctions in TheoryEngine::rewrite().

* add gmpxx detection and inclusion

* better Asserts throughout, some documentation, cleanup

diff --git a/src/expr/mkkind b/src/expr/mkkind
--- a/src/expr/mkkind
+++ b/src/expr/mkkind
@@ -5,7 +5,7 @@
 # Copyright (c) 2010  The CVC4 Project
 #
 # The purpose of this script is to create kind.h from a prologue,
-# middle, epilogue, and a list of theory kinds.
+# middle section, epilogue, and a list of theory kinds.
 #
 # Invocation:
 #
@@ -14,11 +14,13 @@
 # Output is to standard out.
 #
 
+copyright=2010
+
 cat <<EOF
 /*********************                                           -*- C++ -*-  */
 /** kind.h
  **
- ** Copyright 2010  The AcSys Group, New York University, and as below.
+ ** Copyright $copyright  The AcSys Group, New York University, and as below.
  **
  ** This header file automatically generated by:
  **
@@ -29,44 +31,125 @@ cat <<EOF
 
 EOF
 
-prologue=$1; shift
-middle=$1; shift
-epilogue=$1; shift
+me=$(basename "$0")
 
-cases=
+template=$1; shift
 
-function special {
-  r=$1
-  comment=$2
+kind_decls=
+kind_printers=
 
-  echo "  $r, /*! $comment */"
-  cases="$cases  case $r: out << \"$r\"; break;
-"
+seen_theory=false
+seen_theory_builtin=false
+
+function theory {
+  # theory T header
+
+  lineno=${BASH_LINENO[0]}
+
+  # this script doesn't care about the theory class information, but
+  # makes does make sure it's there
+  seen_theory=true
+  if [ "$1" = builtin ]; then
+    if $seen_theory_builtin; then
+      echo "$kf:$lineno: error: \"builtin\" theory redefined" >&2
+      exit 1
+    fi
+    seen_theory_builtin=true
+  elif [ -z "$1" -o -z "$2" ]; then
+    echo "$kf:$lineno: error: \"theory\" directive missing class or header argument" >&2
+    exit 1
+  elif ! expr "$1" : '\(::*\)' >/dev/null; then
+    echo "$kf:$lineno: warning: theory class \`$1' isn't fully-qualified (e.g., ::CVC4::theory::foo)" >&2
+  elif ! expr "$1" : '\(::CVC4::theory::*\)' >/dev/null; then
+    echo "$kf:$lineno: warning: theory class not under ::CVC4::theory namespace" >&2
+  fi
+}
+
+function variable {
+  # variable K ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  check_theory_seen
+  register_kind "$1" 0 "$2"
 }
 
 function operator {
-  special "$1" "$2"
+  # operator K #children ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  check_theory_seen
+  register_kind "$1" "$2" "$3"
 }
 
 function parameterized {
-  special "$1" "$2"
+  # parameterized K #children ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  check_theory_seen
+  register_kind "$1" "$2" "$3"
 }
 
 function constant {
-  special "$1" "$3"
+  # constant K T Hasher header ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  check_theory_seen
+  register_kind "$1" 0 "$5"
 }
 
-cat "$prologue"
+function register_kind {
+  r=$1
+  nc=$2
+  comment=$3
+
+  kind_decls="${kind_decls}  $r, /*! $comment */
+"
+  kind_printers="${kind_printers}  case $r: out << \"$r\"; break;
+"
+}
+
+function check_theory_seen {
+  if ! $seen_theory; then
+    echo "$kf:$lineno: error: no \"theory\" declaration found (it has to be first)" >&2
+    exit 1
+  fi
+}
+
+function check_builtin_theory_seen {
+  if ! $seen_theory_builtin; then
+    echo "$me: warning: no declaration for the builtin theory found" >&2
+  fi
+}
+
 while [ $# -gt 0 ]; do
-  b=$(basename $(dirname "$1"))
-  echo
-  echo "  /* from $b */"
-  cases="$cases
+  kf=$1
+  seen_theory=false
+  b=$(basename $(dirname "$kf"))
+  kind_decls="${kind_decls}
   /* from $b */
 "
-  source "$1"
+  kind_printers="${kind_printers}
+  /* from $b */
+"
+  source "$kf"
+  check_theory_seen
   shift
 done
-cat "$middle"
-echo "$cases"
-cat "$epilogue"
+check_builtin_theory_seen
+
+## output
+
+text=$(cat "$template")
+for var in kind_decls kind_printers; do
+  eval text="\${text//\\\$\\{$var\\}/\${$var}}"
+done
+error=`expr "$text" : '.*\${\([^}]*\)}.*'`
+if [ -n "$error" ]; then
+  echo "$template:0: error: undefined replacement \${$error}" >&2
+  exit 1
+fi
+echo "$text"
diff --git a/src/theory/mktheoryof b/src/theory/mktheoryof
--- a/src/theory/mktheoryof
+++ b/src/theory/mktheoryof
@@ -14,11 +14,13 @@
 # Output is to standard out.
 #
 
+copyright=2010
+
 cat <<EOF
 /*********************                                           -*- C++ -*-  */
 /** theoryof_table.h
  **
- ** Copyright 2010  The AcSys Group, New York University, and as below.
+ ** Copyright $copyright  The AcSys Group, New York University, and as below.
  **
  ** This header file automatically generated by:
  **
@@ -29,47 +31,108 @@ cat <<EOF
 
 EOF
 
-prologue=$1; shift
-middle=$1; shift
-epilogue=$1; shift
+template=$1; shift
 
-registers=
+theoryof_table_includes=
+theoryof_table_registers=
 
-function special {
-  r=$1
-  comment=$2
+seen_theory=false
+seen_theory_builtin=false
 
-  registers="$registers    d_table[::CVC4::kind::$r] = th;
+function theory {
+  lineno=${BASH_LINENO[0]}
+
+  # this script doesn't care about the theory class information, but
+  # makes does make sure it's there
+  seen_theory=true
+  if [ "$1" = builtin ]; then
+    if $seen_theory_builtin; then
+      echo "$kf:$lineno: error: \"builtin\" theory redefined" >&2
+      exit 1
+    fi
+    seen_theory_builtin=true
+  elif [ -z "$1" -o -z "$2" ]; then
+    echo "$kf:$lineno: error: \"theory\" directive missing class or header argument" >&2
+    exit 1
+  elif ! expr "$1" : '\(::*\)' >/dev/null; then
+    echo "$kf:$lineno: warning: theory class \`$1' isn't fully-qualified (e.g., ::CVC4::theory::foo)" >&2
+  elif ! expr "$1" : '\(::CVC4::theory::*\)' >/dev/null; then
+    echo "$kf:$lineno: warning: theory class not under ::CVC4::theory namespace" >&2
+  fi
+
+  theoryof_table_includes="${theoryof_table_includes}#include \"theory/$b/$2\"
 "
+  theoryof_table_registers="${theoryof_table_registers}
+  /* from $b */
+  void registerTheory($1* th) {
+"
+}
+
+function variable {
+  # variable K ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  do_theoryof "$1"
 }
 
 function operator {
-  special "$1" "$2"
+  # operator K #children ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  do_theoryof "$1"
 }
 
 function parameterized {
-  special "$1" "$2"
+  # parameterized K #children ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  do_theoryof "$1"
 }
 
 function constant {
-  special "$1" "$3"
+  # constant K T Hasher header ["comment"]
+
+  lineno=${BASH_LINENO[0]}
+
+  do_theoryof "$1"
 }
 
-cat "$prologue"
-while [ $# -gt 0 ]; do
-  b=$(basename $(dirname "$1"))
-  B=$(echo "$b" | tr 'a-z' 'A-Z')
-  echo "#include \"theory/$b/theory_def.h\""
-  registers="$registers
-  /* from $b */
-  void registerTheory(::CVC4::theory::$b::Theory$B* th) {
+function do_theoryof {
+  check_theory_seen
+  theoryof_table_registers="${theoryof_table_registers}    d_table[::CVC4::kind::$1] = th;
 "
-  source "$1"
-  registers="$registers  }
+}
+
+function check_theory_seen {
+  if ! $seen_theory; then
+    echo "$kf:$lineno: error: no \"theory\" declaration found (it has to be first)" >&2
+    exit 1
+  fi
+}
+
+while [ $# -gt 0 ]; do
+  kf=$1
+  seen_theory=false
+  b=$(basename $(dirname "$kf"))
+  source "$kf"
+  check_theory_seen
+  theoryof_table_registers="${theoryof_table_registers}  }
 "
   shift
 done
-echo
-cat "$middle"
-echo "$registers"
-cat "$epilogue"
+
+## output
+
+text=$(cat "$template")
+for var in theoryof_table_includes theoryof_table_registers; do
+  eval text="\${text//\\\$\\{$var\\}/\${$var}}"
+done
+error=`expr "$text" : '.*\${\([^}]*\)}.*'`
+if [ -n "$error" ]; then
+  echo "$template:0: error: undefined replacement \${$error}" >&2
+  exit 1
+fi
+echo "$text"
