Fix bug 476: when CxxTest is not found, make the error less fatal-looking

diff --git a/test/unit/no_cxxtest b/test/unit/no_cxxtest
--- a/test/unit/no_cxxtest
+++ b/test/unit/no_cxxtest
@@ -3,10 +3,10 @@
 echo
 echo '***************************************************************************'
 echo '*                                                                         *'
-echo '*  ERROR:  CxxTest was not found at configure-time; tests cannot be run.  *'
+echo '*   WARNING:  CxxTest not found at configure time; tests cannot be run.   *'
 echo '*                                                                         *'
 echo '***************************************************************************'
 echo
 
-exit 1
-
+# skip this test, rather than reporting an error
+exit 77
